// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func hello(name string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html><head><script src=\"https://unpkg.com/htmx.org@1.9.10\"></script><script type=\"importmap\">\n\t\t\t{\n\t\t\t\t\"imports\": {\n\t\t\t\t\t\"react\": \"https://esm.sh/react@19.1.0?dev\",\n\t\t\t\t\t\"react-dom\": \"https://esm.sh/react-dom@19.1.0?dev\",\n\t\t\t\t\t\"react-dom/client\": \"https://esm.sh/react-dom@19.1.0/client?dev\",\n\t\t\t\t\t\"react/jsx-runtime\": \"https://esm.sh/react@19.1.0/jsx-runtime?dev\"\n\t\t\t\t}\n\t\t\t}\n\t\t\t</script><script type=\"module\">\n\t\t\t\timport { Example } from \"/react/dist/example.js\"\n\t\t\t</script></head><body><button id=\"boom\" hx-get=\"/boom\" hx-target=\"body\" style=\"display:none;\" hidden=\"true\"></button> <the-example text=\"Click me\" callback=\"onCallback\"></the-example><div id=\"result\"></div><script>\n\t\t\t\tfunction onCallback() {\n\t\t\t\t\tdocument.getElementById('boom').click();\n\t\t\t\t}\n\t\t\t</script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
